name: taxinet_driver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http:
  get:
  get_storage:
  badges:
  url_launcher:
  flutter_local_notifications:
  rxdart:
  dio:
  modal_bottom_sheet:
  animated_text_kit:
  file_picker:
  image_picker:
  image_cropper:
  lottie:
  provider:
  google_fonts:
  flutter_switch:
  connectivity_plus:
  internet_connection_checker:
  sliding_up_panel:
  flip_card:
  fab_circular_menu:
  animate_do:
  water_drop_nav_bar:
  font_awesome_flutter: ^10.1.0
  loader_skeleton: ^0.0.4
  flutter_phone_direct_caller: ^2.1.1
  shimmer: ^2.0.0
  google_maps_flutter: ^2.2.0
  location:
  geolocator:
  geocoding:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/json/
    - assets/sounds/


  fonts:
    - family: Sansita Swashed
      fonts:
        - asset: assets/fonts/SansitaSwashed-VariableFont_wght.ttf

